// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSpgaEvU4LfUOwF4gc6ICd7qmuy3tXal8',
    appId: '1:157572492234:web:51c3c4fc601fd338f67d33',
    messagingSenderId: '157572492234',
    projectId: 'ecommercefoodieapp',
    authDomain: 'ecommercefoodieapp.firebaseapp.com',
    storageBucket: 'ecommercefoodieapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdl9WNCuXJoH1hLqU1JlUeLG3EcaGy_KU',
    appId: '1:157572492234:android:510fb7265321b8c6f67d33',
    messagingSenderId: '157572492234',
    projectId: 'ecommercefoodieapp',
    storageBucket: 'ecommercefoodieapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcydtIbXeZxsNYNbcndJDBwXEswSa-IWw',
    appId: '1:157572492234:ios:502d0b449c445447f67d33',
    messagingSenderId: '157572492234',
    projectId: 'ecommercefoodieapp',
    storageBucket: 'ecommercefoodieapp.appspot.com',
    iosClientId: '157572492234-oqq78ribd2b0a58tmsklt7k6nio2bp1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcydtIbXeZxsNYNbcndJDBwXEswSa-IWw',
    appId: '1:157572492234:ios:502d0b449c445447f67d33',
    messagingSenderId: '157572492234',
    projectId: 'ecommercefoodieapp',
    storageBucket: 'ecommercefoodieapp.appspot.com',
    iosClientId: '157572492234-oqq78ribd2b0a58tmsklt7k6nio2bp1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
